Infinite Scroll Example
riot/examples pull request #35
Opened 2016-11-02 08:56 UTC by Ke-

Added basic infinite scroll example. Works great with thousands of tags.

2016-11-02 15:40 UTC, cognitom requested changes
Hi @Ke-, thanks for your PR! I like it.
LGTM, basically about the logic. I've left some review comments. Could you check them?

2016-11-02 15:40 UTC, cognitom commented on infinite-list/infinite-list.css
> +	display: block;
Pls use 2 spaces instead of tab. There're some indentation errors in other files, too. Check it.

2016-11-02 15:40 UTC, cognitom commented on infinite-list/list-item.tag
> +    this.update()
Why `preventUpdate`, with `this.update()`?

2016-11-02 15:40 UTC, cognitom commented on infinite-list/infinite-list.tag
> +
Could you use `<script>` tag here? Basically we encourage to put the JavaScript into `<script>` in this repo, basically.

2016-11-02 15:40 UTC, cognitom commented on infinite-list/list-item.tag
> +
`<script>`

2016-11-02 15:40 UTC, cognitom commented on infinite-list/infinite-list.css
> +infinite-list{
I prefer to move this style to the `<infinite-list>` tag. Thought?

2016-11-02 15:40 UTC, cognitom commented on infinite-list/index.html
> +    <script>html5.addElements('todo')</script>
??

2016-11-02 15:40 UTC, cognitom commented on infinite-list/infinite-list.tag
> +    var itemheight  = 72  // Height of item
I'm not sure, I couldn't find the style which define this height. I wonder it depends on environment...?

2016-11-02 20:53 UTC, GianlucaGuarini commented
@cognitom thanks for reviewing it!

2017-07-12 19:43 UTC, GianlucaGuarini commented
closing this due to inactivity

2017-07-12 19:43 UTC, closed without merging